services:

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  defra-id-stub:
    image: defradigital/cdp-defra-id-stub:latest
    ports:
      - '3200:3200'
    environment:
      PORT: 3200
      REDIS_HOST: redis
      REDIS_PORT: 6380
      USE_SINGLE_INSTANCE_CACHE: true
      NODE_ENV: development
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3200/health']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      cdp-tenant:
        aliases:
          - localhost

  caddy:
    image: caddy:2-alpine
    ports:
      - '4000:4000'
    volumes:
      - ./compose/Caddyfile:/etc/caddy/Caddyfile:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - cdp-tenant


################################################################################

#  your-frontend:
#    build: ./
#    ports:
#      - '3000:3000'
#    links:
#      - 'localstack:localstack'
#      - 'redis:redis'
#    depends_on:
#      localstack:
#        condition: service_healthy
#      redis:
#        condition: service_started
#    env_file:
#      - 'compose/aws.env'
#    environment:
#      PORT: 3000
#      NODE_ENV: development
#      REDIS_HOST: redis
#      LOCALSTACK_ENDPOINT: http://localstack:4566
#      USE_SINGLE_INSTANCE_CACHE: true
#    networks:
#      - cdp-tenant

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
