name: Journey Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Publish']
    types:
      - completed

jobs:
  test:
    uses: DEFRA/nrf-journey-tests/.github/workflows/journey-tests.yml@main
